apiVersion: v1
kind: Template
metadata:
  name: kibana-persistent
  annotations:
    openshift.io/display-name: 'Kibana'
    description: "Kibana. Viewer and adminsitration for ElasticSearch."
    tags: "searchengine,database,elasticsearch,kibana,logs,administration"
    iconClass: "icon-kibana"
  
parameters:
  - name: KIBANA_NAME
    displayName: "Kibana Name"
    description: "A name for your Kibana instance."
    from: "[a-zA-Z0-9]{10}"
    value: "kibana"
    required: true
    
  - name: ELASTICSEARCH_HOST_URL
    displayName: "ElasticSearch Host URL"
    description: "A reference to ElasticSearch your ElasticSearch instance."
    from: "[a-zA-Z0-9]{10}"
    value: "elasticsearch"
    required: true
    
  - name: KIBANA_DOMAIN_URL
    displayName: "Kibana Domain URL"
    description: "A reference to Kibana domain URL."
    from: "[a-zA-Z0-9]{100}"    
    
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${KIBANA_NAME}
    spec:
      ports:
      - name: "kibana-http"
        port: 5601
        protocol: TCP
        targetPort: 5601
      selector:
        deploymentconfig: ${KIBANA_NAME}
      
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${KIBANA_NAME}"
    spec:
      host: ${KIBANA_DOMAIN_URL}
      to:
        kind: Service
        name: ${KIBANA_NAME}
      port:
        targetPort: kibana-http
        
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        component: kibana
        provider: openshift
      name: ${KIBANA_NAME}
    spec:
      replicas: 1
      selector:
        component: kibana
        provider: openshift
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            component: kibana
            provider: openshift
          name: kibana
        spec:
          serviceAccountName: kibana
          containers:
          - env:
            - name: ELASTICSEARCH_URL
              value: ${ELASTICSEARCH_HOST_URL}
            image: kibana
            imagePullPolicy: Always
            name: kibana
            ports:
            - containerPort: 5601
              name: kibana
              
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - kibana
          from:
            kind: ImageStreamTag
            name: docker.elastic.co/kibana/kibana:8.5.3
        type: ImageChange

