kind: List
apiVersion: v1
metadata: {}

items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv1
    spec:
      capacity:
        storage: 50Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeClaim: Retain
      hostPath:
        path: /mnt/openshift-pv/pv1
