apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gallery-cron
spec:
  schedule: "*/1 * * * *"       
  concurrencyPolicy: "Replace"  
  startingDeadlineSeconds: 200  
  suspend: false                
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1     
  jobTemplate:                  
    spec:
      template:
        metadata:
          labels:               
            parent: "cronjobphotoutil"
        spec:
          volumes:
          - name: secret-volume
            secret:
            secretName: cronjobs
          - name: volume-e2asw
            persistentVolumeClaim:
              claimName: photos
          containers:
          - name: gallery-util-2ff
            image: 172.30.1.1:5000/test2/gallery-util-2ff
            volumeMounts:
            - mountPath: /mnt/photos
              name: volume-e2asw
          restartPolicy: OnFailure 